### ISSUE TITLE
Fix indel matching

### ISSUE THREAD

**Issue by naqvia** [diskin-lab-chop/pathogenicity-assessment#6]
Fix matching so variants ids match between the different tables (clinvar, intervar and autopvs1).

**Comment by migbro** [comment]
Revisiting this and working on it a bit with Ammar. To summarize:
 - Annovar txt file is used for some of the criteria, but adjustments it makes to coordinates for indels makes it difficult
 - Saksham addressed this by adding the flag `vcfinput` so that a vcf file is output, however
   - Current wf converts input vcf to av input
   - This was done because using vcf input directly caused large run times
   - correct interpretation is, since input in workflow to that step is a converted vcf to av input file, vcfinput flag should not be used, but that means a vcf file to help guide correct position, ref, alt, is not output
 - I think I might havea solution that balances performance with accuracy - for the annovar step, the `CSQ` from VEP is not needed, stripping this before annovar, giving it the vcf and adding that flag satisfies all conditions AFAIK. @naqvia will verify

If the above solution is sufficient, I can modify the workflow to reflect this change, should not take long. Example of update annovar output (autpvs1 and intervar not run yet!) is here: https://cavatica.sbgenomics.com/u/d3b-bixu/d3b-diskin-pathogenicity-dev/tasks/c9fa363f-8f06-41ed-a59c-575465f069ac/

**Comment by jharenza** [comment]
Thanks for working on this @migbro . I was also thinking, would it be possible to run annovar on an INDEL vcf and SNVs on your av input file, and combine after - probably more work, but just an idea to cut down time.

**Comment by migbro** [comment]
Not a bad idea, but I think the strip step + vcf input for both will work just fine. I found that stripping the CSQ significantly cut down on run time and the strip step takes less than 10 minutes.

**Comment by jharenza** [comment]
ok cool 👍

**Comment by naqvia** [comment]
Thank you for working on this @migbro! So yes, this seems to be what we would want! Just to show you an example: 

```
(base) DCR6034KVC:Downloads naqvia$ cat DELME_TEST_VCF_CSQ_STRIPPED.hg38_multianno.txt  | awk -F "\t" '{print $1"\t"$2"\t"$3"\t"$150"\t"$151"\t"$152"\t"$153"\t"$154}' | grep "rs200672483"
chr1	61351	61351	chr1	61350	rs200672483	TA	T
```

This is a case where the coordinates (first three items) differ from the "OtherInfo" coordinates. The columns I would get this info is from`Otherinfo4`	`Otherinfo5`	`Otherinfo6`	`Otherinfo7`	`Otherinfo8`. The coordinates in the `Otherinfo` fields should match the clinVar, autoPVS1 coordinates. 

Just as a sanity check, can we run interVar and autopvs1 on this sample and confirm that they indeed match up with these OtherInfo coordinates?

**Comment by migbro** [comment]
Sure, so given autovs1 runs on the VEP input only, you can use the old output from this task directly: https://cavatica.sbgenomics.com/u/d3b-bixu/d3b-diskin-pathogenicity-dev/tasks/7aefaa8b-3dbe-4fe2-afb1-6f95d132ec87/. Testing InterVar here: https://cavatica.sbgenomics.com/u/d3b-bixu/d3b-diskin-pathogenicity-dev/tasks/6f8c67c5-6c4d-44f7-87a6-c410c6287124/#

**Comment by naqvia** [comment]
Great Yes it matches!

**Comment by naqvia** [comment]
This looks great! Lets finalize this!

**Comment by migbro** [comment]
Cool! I'll get to it when I can, as it seems this repo is to become more analysis-only. So I'll be moving the cwl code to D3b and blowing it away from this one

**Comment by jharenza** [comment]
this is complete
